services:
  app1:
    build: ./app
    container_name: app1
    expose:
      - "8000"
    networks:
      - app_network

  app2:
    build: ./app
    container_name: app2
    expose:
      - "8000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge