name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write  # Allow pushing to GitHub Container Registry
      contents: read   # Default read access to repository contents

    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Build the Docker image from the `app` directory
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/loadbalancer-test:latest -f ./app/Dockerfile ./app

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/loadbalancer-test:latest
