name: Build and Push Docker Image

# Trigger the workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write  # Allow the workflow to push to GitHub Container Registry
      contents: read   # Default read access to repository contents

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry using the built-in GITHUB_TOKEN
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/loadbalancer-test:latest .

      # Step 4: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/loadbalancer-test:latest
